# Generated by Django 3.1.4 on 2020-12-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(db_column='movie_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('language', models.CharField(blank=True, max_length=45, null=True)),
                ('director', models.CharField(blank=True, max_length=40, null=True)),
                ('genre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovieShowtime',
            fields=[
                ('showtime_id', models.IntegerField(db_column='showtime_ID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('screening_category', models.CharField(blank=True, max_length=10, null=True)),
                ('subtitles', models.IntegerField(blank=True, null=True)),
                ('voiceover', models.IntegerField(blank=True, null=True)),
                ('dubbing', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movie_showtime',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('seat_id', models.IntegerField(db_column='seat_ID', primary_key=True, serialize=False)),
                ('row', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'seat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(db_column='ticket_ID', primary_key=True, serialize=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('price_category', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.IntegerField(db_column='hall_ID', primary_key=True, serialize=False)),
                ('seats_number', models.IntegerField(blank=True, null=True)),
                ('hall_category', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'hall',
            },
        ),
    ]
